INSERT INTO GENDERS (NAME) VALUES ('HOMBRE');
INSERT INTO GENDERS (NAME) VALUES ('MUJER');
INSERT INTO GENDERS (NAME) VALUES ('OTRO');

INSERT INTO JOBS (NAME,SALARY) VALUES ('RECURSOS HUMANOS',100.0);
INSERT INTO JOBS (NAME,SALARY) VALUES ('VENTAS',120.0);
INSERT INTO JOBS (NAME,SALARY) VALUES ('SISTEMAS',125.0);
INSERT INTO JOBS (NAME,SALARY) VALUES ('ADMIN PROYECTOS',120.0);
INSERT INTO JOBS (NAME,SALARY) VALUES ('GERENCIA',150.0);


INSERT INTO EMPLOYEES (ID, GENDER_ID, JOB_ID, NAME, LAST_NAME, BIRTHDATE) VALUES(1, 1, 1, 'Juan', 'Pérez', '1982-12-31');
INSERT INTO EMPLOYEES (ID, GENDER_ID, JOB_ID, NAME, LAST_NAME, BIRTHDATE) VALUES(4, 1, 1, 'Luis', 'Pérez', '1992-12-31');
INSERT INTO EMPLOYEES (ID, GENDER_ID, JOB_ID, NAME, LAST_NAME, BIRTHDATE) VALUES(5, 2, 2, 'Laura', 'Torres', '2002-06-10');

INSERT INTO EMPLOYEE_WORKED_HOURS (ID, EMPLOYEES_ID, WORKED_HOURS, WORKED_DATE) VALUES(1, 1, 10, '2018-12-31');
INSERT INTO EMPLOYEE_WORKED_HOURS (ID, EMPLOYEES_ID, WORKED_HOURS, WORKED_DATE) VALUES(2, 1, 20, '2022-06-24');
INSERT INTO EMPLOYEE_WORKED_HOURS (ID, EMPLOYEES_ID, WORKED_HOURS, WORKED_DATE) VALUES(3, 1, 20, '2022-06-23');
INSERT INTO EMPLOYEE_WORKED_HOURS (ID, EMPLOYEES_ID, WORKED_HOURS, WORKED_DATE) VALUES(4, 4, 20, '2022-06-24');
INSERT INTO EMPLOYEE_WORKED_HOURS (ID, EMPLOYEES_ID, WORKED_HOURS, WORKED_DATE) VALUES(5, 4, 20, '2021-06-24');

